[build-system]
requires = [
    "pybind11",
    "setuptools>=42",
    "wheel",
]

build-backend = "setuptools.build_meta"

[project]
name = "vshogi"
version = "0.0.3"
description = "Shogi API for Shogi and its variants"
readme = "README.md"
requires-python = ">=3.10"
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
authors = [
    {name = "ctgk", email = "r1135nj54w@gmail.com"}
]
dependencies = [
    "numpy",
]

[project.urls]
Homepage = "https://github.com/ctgk/vshogi"

[project.optional-dependencies]
develop = [
    # TODO: Unpin when ai-edge-litert >1.4.0 is released that
    # fixes macOS ARM64 wheels
    # https://github.com/google-ai-edge/LiteRT/issues/2836
    "ai-edge-litert==1.2.0; sys_platform == 'darwin'",
    "ai-edge-torch==0.4.0; sys_platform == 'darwin'",
    "jax < 0.7.0; sys_platform == 'darwin'",
    "ai-edge-litert; sys_platform != 'darwin'",
    "ai-edge-torch; sys_platform != 'darwin'",

    "pandas",
    "torch",
    "tqdm",
    "pre-commit",
    "pybind11",
    "pytest",
    "ruff",
]
dlshogi = [
    # TODO: Unpin when ai-edge-litert >1.4.0 is released that
    # fixes macOS ARM64 wheels
    # https://github.com/google-ai-edge/LiteRT/issues/2836
    "ai-edge-litert==1.2.0; sys_platform == 'darwin'",
    "ai-edge-torch==0.4.0; sys_platform == 'darwin'",
    "jax < 0.7.0; sys_platform == 'darwin'",
    "ai-edge-litert; sys_platform != 'darwin'",
    "ai-edge-torch; sys_platform != 'darwin'",

    "click",
    "joblib",
    "pandas",
    "torch",
    "tqdm",
]

[tool.setuptools.packages.find]
where = ["python"]
include = ["vshogi*"]
exclude = ["test*"]

[tool.pytest.ini_options]
addopts = [
    "--doctest-modules",
    "--ignore=python/scripts/",
    "--ignore=python/vshogi/_cli",
    "--ignore=python/vshogi/dlshogi/_cli_nn_trainer.py",
    "--ignore=python/vshogi/__main__.py",
]
testpaths = ["python/"]

[tool.ruff]
line-length = 79
indent-width = 4
exclude = [
    "python/scripts/*.py",
    "python/vshogi/__main__.py",
    ".github/workflows/*.py",
    "setup.py",
]

[tool.ruff.lint]
# select = ["E4", "E7", "E9", "F"] <- default
select = ["A", "E", "F"]
ignore = [
    # "D105",  # Missing docstring in magic method
    "F821",  # undefined name ...
    # "W503",  # line break before binary ooperator
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

[tool.ruff.lint.isort]
lines-after-imports = 2
known-first-party = ["vshogi"]

[tool.ruff.lint.per-file-ignores]
"python/tests/**.py" = [
    "D100",  # Missing docstring in public module
    "D101",  # Missing docstring in public class
    "D102",  # Missing docstring in public method
    "D103",  # Missing docstring in public function
    "D104",  # Missing docstring in public package
    "S101",  # Use of `assert`
]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.format]
quote-style = "preserve"
indent-style = "space"
line-ending = "lf"
skip-magic-trailing-comma = false
docstring-code-format = false
docstring-code-line-length = "dynamic"
