[build-system]
requires = ["scikit-build-core >=0.10", "nanobind >=1.3.2"]
build-backend = "scikit_build_core.build"

[project]
name = "vshogi"
version = "0.0.3"
description = "Shogi API for Shogi and its variants"
readme = "README.md"
requires-python = ">=3.10"
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
authors = [
    {name = "ctgk", email = "r1135nj54w@gmail.com"}
]
dependencies = [
    "numpy",
    "scipy",
]

[project.urls]
Homepage = "https://github.com/ctgk/vshogi"

[project.optional-dependencies]
develop = [
    "ai-edge-litert",
    "litert-torch",

    "pandas",
    "torch",
    "tqdm",
    "pre-commit",
    "nanobind",
    "pytest",
    "ruff",
]
dlshogi = [
    "ai-edge-litert",
    "litert-torch",

    "click",
    "joblib",
    "pandas",
    "torch",
    "tqdm",
]

[tool.setuptools.packages.find]
where = ["python"]
include = ["vshogi*"]
exclude = ["test*"]

[tool.scikit-build]
# Protect the configuration against future changes in scikit-build-core
minimum-version = "build-system.requires"

# Setuptools-style build caching in a local directory
build-dir = "build/{wheel_tag}"

# Source directory for CMake
cmake.source-dir = "cpp/python"

# Build stable ABI wheels for CPython 3.12+
wheel.py-api = "cp312"

# Install the Python package into the vshogi directory
# This tells scikit-build-core where to place compiled extensions
wheel.install-dir = "vshogi"

[tool.pytest.ini_options]
addopts = [
    "--doctest-modules",
    "--ignore=python/scripts/",
    "--ignore=python/vshogi/_cli",
    "--ignore=python/vshogi/dlshogi/_cli_nn_trainer.py",
    "--ignore=python/vshogi/__main__.py",
]
testpaths = ["python/"]

[tool.ruff]
line-length = 79
indent-width = 4
exclude = [
    "python/scripts/*.py",
    "python/vshogi/__main__.py",
    ".github/workflows/*.py",
    "setup.py",
]

[tool.ruff.lint]
# select = ["E4", "E7", "E9", "F"] <- default
select = [
    "A",  # flake8-builtins
    "E",  # pycodestyle
    "F",  # pyflakes
    "T100",  # flake8-debugger
]
ignore = [
    # "D105",  # Missing docstring in magic method
    "F821",  # undefined name ...
    # "W503",  # line break before binary ooperator
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

[tool.ruff.lint.isort]
lines-after-imports = 2
known-first-party = ["vshogi"]

[tool.ruff.lint.per-file-ignores]
"python/tests/**.py" = [
    "D100",  # Missing docstring in public module
    "D101",  # Missing docstring in public class
    "D102",  # Missing docstring in public method
    "D103",  # Missing docstring in public function
    "D104",  # Missing docstring in public package
    "S101",  # Use of `assert`
]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.format]
quote-style = "preserve"
indent-style = "space"
line-ending = "lf"
skip-magic-trailing-comma = false
docstring-code-format = false
docstring-code-line-length = "dynamic"
