[build-system]
requires = [
    "pybind11",
    "setuptools>=42",
    "wheel",
]

build-backend = "setuptools.build_meta"

[tool.pytest]
addopts = [
    "--doctest-modules",
    "--ignore=python/scripts/",
    "--ignore=python/vshogi/_cli",
    "--ignore=python/vshogi/dlshogi/_cli_nn_trainer.py",
    "--ignore=python/vshogi/__main__.py",
]
testpaths = ["python/"]
