; See:
; https://setuptools.readthedocs.io/en/latest/userguide/declarative_config.html

[metadata]
name = vshogi
version = 0.0.2
description = Shogi API for Shogi and its variants
url = https://github.com/ctgk/vshogi
author = ctgk
author_email = r1135nj54w@gmail.com
license = GPLv3
license_files = LICENSE
long_description = file: README.md
long_description_content_type = text/markdown

[options]
python_requires = >=3.10
install_requires =
    numpy
    scipy
packages = find:
package_dir =
    =python

[options.packages.find]
where = python
include = vshogi*
exclude = test*

[options.extras_require]
develop =
    ai-edge-litert
    ai-edge-torch
    jax < 0.7.0
    pandas
    torch
    tqdm

    pre-commit
    pybind11
    pytest
    ruff

dlshogi =
    ai-edge-litert
    ai-edge-torch
    jax < 0.7.0
    click
    joblib
    pandas
    torch
    tqdm
