name: Run C++ Profiling

on:
  push:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: install packages
      run: sudo apt update -y; sudo apt install -y build-essential make cpputest libc++-dev
    - name: Run command
      run: mkdir build; cd build; cmake -DCMAKE_CXX_FLAGS=-pg -DCMAKE_EXE_LINKER_FLAGS=-pg -DCMAKE_SHARED_LINKER_FLAGS=-pg ../cpp; make; ./tests/test_vshogi -r10 -g shogi_engine -n mcts_with_dfpn; gprof ./tests/test_vshogi gmon.out
