name: Run C++ Profiling

on:
  push:
    branches: [ main, develop, tmp ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [
          {num: 20, test_case: mcts_with_dfpn},
          {num:  1, test_case: random_playout_searcher},
        ]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: install packages
      run: sudo apt update -y; sudo apt install -y build-essential make cpputest libc++-dev
    - name: Build
      run: cmake -DCMAKE_CXX_FLAGS=-pg -DCMAKE_EXE_LINKER_FLAGS=-pg -DCMAKE_SHARED_LINKER_FLAGS=-pg ./cpp; make
    - name: Execute
      env:
        NUM: ${{ matrix.config.num }}
        TESTCASE: ${{ matrix.config.test_case }}
      run: ./tests/test_vshogi -r$NUM -g shogi_engine -n $TESTCASE
    - name: Profile
      run: gprof ./tests/test_vshogi gmon.out
