name: Run DL-Shogi Training

on:
  push:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']
        command: [
          "pip install .[dlshogi]; python examples/dlshogi.py rl animal_shogi --rl_cycle 5 --mcts_explorations 100 --self_play 200 --win_ratio_threshold 0.1",
          "pip install .[dlshogi]; python examples/dlshogi.py rl minishogi --rl_cycle 4 --mcts_explorations 100 --self_play 100 --win_ratio_threshold 0.1",
          "pip install .[dlshogi]; python examples/dlshogi.py rl judkins_shogi --rl_cycle 3 --mcts_explorations 100 --self_play 100 --win_ratio_threshold 0.1",
          "pip install .[dlshogi]; python examples/dlshogi.py rl shogi --rl_cycle 1 --nn_backbones 2 --mcts_explorations 100 --self_play 100 --win_ratio_threshold 0.1",
        ]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
    - name: Run command
      env:
        CMD: ${{ matrix.command }}
      run: bash -c "$CMD"
