# This workflow will install Python dependencies, run full checks defined in `.pre-commit-config.yaml` with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Check Repository

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
        command: [
          "pip install .; pip install pytest; pytest --doctest-modules --import-mode=importlib python/",
          "pip install -e .[develop]; SKIP=no-commit-to-branch pre-commit run -a"
        ]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
    - name: install packages
      run: sudo apt update -y; sudo apt install -y build-essential make cpputest clang-format-12 clang-tidy-11 libc++-dev
    - name: Run command
      env:
        CMD: ${{ matrix.command }}
      run: bash -c "$CMD"
