name: Run CLI Training

on:
  push:
    branches: [ main, develop, tmp ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        algorithm: ["alpha-zero", "gumbel-alpha-zero"]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
    - name: Install dependencies
      run: pip install .[dlshogi]
    - name: Run command
      env:
        ALGORITHM: ${{ matrix.algorithm }}
      run: |
        python -m vshogi $ALGORITHM cycler minishogi \
        --cycles 3 --play-num-games 50 \
        --train-network-blocks 3 --train-validation-threshold 0.01
    - name: Evaluate model
      run: |
        python -m vshogi match minishogi \
        --player1 models/model_0000.tflite \
        --player2 models/model_0003.tflite \
        --az-search-count 100
    - name: Check generated dataset
      run: |
        for tsv in datasets/dataset_*/kifu_*.tsv; do
          echo "$tsv"
          cat "$tsv"
          python .github/workflows/check_selfplay_dataset.py "$tsv"
        done
